
enum ChangeType {
    INSERT_ROW="INSERT_ROW",
    UPDATE_ROW="UPDATE_ROW",
    DELETE_ROW="DELETE_ROW",
    INSERT_CATEGORY="INSERT_CATEGORY",
    DELETE_CATEGORY="DELETE_CATEGORY",
    QUANTITY_INCREASE="QUANTITY_INCREASE",
    QUANTITY_REDUCTION="QUANTITY_REDUCTION"
};

export default ChangeType;